# Generated by Django 3.0.3 on 2020-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200517_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='posts_number',
            field=models.IntegerField(default=0),
        ),
    ]
